server:
  port: 8080
app:
  public-url: https://improved-space-succotash-9r7qqvwr69whpjvx-8080.app.github.dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobseeker_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dummy@gmail.com
    password: dummy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

profile:
  name: Abhiram Rote
  phone: "+917286951917"
  email: abhiramrote@gmail.com
  min-experience: 1
  max-experience: 3

  skills:
    - java
    - spring boot
    - spring
    - python
    - flask
    - fastapi
    - rest api
    - microservices
    - jpa
    - hibernate
    - mysql
    - sql
    - javascript
    - react
    - git
    - maven
    - llm
    - rag
    - genai
    - ai
    - openai
    - gpt
    - chromadb
    - vector database
    - docker
    - kafka
    - redis

  target-roles:
    - software engineer
    - backend engineer
    - java developer
    - backend developer
    - sde
    - software developer
    - full stack
    - application developer
    - platform engineer
    - api developer
    - ai engineer
    - ml engineer
    - genai

  locations:
    - hyderabad
    - bangalore
    - bengaluru
    - pune
    - mumbai
    - remote
    - india
    - work from home

  keywords:
    - java
    - spring boot
    - backend
    - microservices
    - rest api
    - python

twilio:
  enabled: ${TWILIO_ENABLED:false}
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  from-whatsapp: ${TWILIO_FROM_WHATSAPP:}
  to-whatsapp: ${TWILIO_TO_WHATSAPP:}


azure:
  openai:
    endpoint: https://your-resource.openai.azure.com
    api-key: your_key_here
    deployment-name: gpt-4o
    api-version: 2024-02-01

scraper:
  target-companies:
    greenhouse:
      - figma
      - airbnb
      - razorpay
      - freshworks
      - browserstack
      - postman
      - datadog
      - snowflakecomputing
    lever:
      - spotify
      - databricks
      - cohere
      - pinecone
    workday: []

logging:
  level:
    com.jobseeker: DEBUG
    com.jobseeker.scraper: INFO
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

